# Generated by Django 5.2.6 on 2025-09-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
